"""headline

Revision ID: 5cebdc06b9fd
Revises: 39cb28455e11
Create Date: 2018-05-23 11:43:45.466160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cebdc06b9fd'
down_revision = '39cb28455e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('headline', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'headline')
    # ### end Alembic commands ###
